// Command dharness is a thin wrapper around react-doctor, fallow and Stryker.
//
// It owns invocation only — scope, order and exit codes. Each tool keeps its
// own configuration, generated by its own init.
package main

import (
	"fmt"
	"os"

	"dharness/internal/app"
)

// version is set via ldflags at build time.
var version = "dev"

func main() {
	app.Version = app.ResolveVersion(version)

	if err := app.Run(); err != nil {
		fmt.Fprintf(os.Stderr, "dharness: %v\n", err)
		os.Exit(app.ExitCode(err))
	}
}
