package setup

import (
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/Disble/dharness/internal/jsconfig"
	"github.com/Disble/dharness/internal/project"
)

// eslintFixtureEnv is the switch that turns this file on. It names an
// absolute path to a disposable project that already has eslint,
// typescript-eslint and dharness-eslint-plugin installed — the verifier
// prepares it, dharness never installs one (§20), and the default suite stays
// offline because an unset variable skips every test here.
const eslintFixtureEnv = "DHARNESS_ESLINT_FIXTURE"

// TestOwnedEslintConfigWithRealESLint is the native verdict for the matchers
// ownedEslintConfig now writes.
//
// The Go tests pin the generated bytes; this one asks ESLint itself, because
// the defect being closed was silence: the owned block had no `files`, so it
// applied only where the project's own matchers already reached. A
// TypeScript-only matcher left `.tsx` unconfigured, ESLint reported nothing
// and exited 0. Only the real binary distinguishes that from a rule that ran
// and found nothing, and the `--print-config` check §11 already uses answers
// that the config *resolves*, which is a different question from whether the
// file is linted.
//
// The cases are the acceptance criteria in executable form: the pre-fix block
// is omitted, the fixed one is judged when a parser exists, fails with
// ESLint's own parsing error when none does, still respects a deliberate
// global ignore, and folds the extension case the way project.IsSourceFile
// does.
func TestOwnedEslintConfigWithRealESLint(t *testing.T) {
	if testing.Short() {
		t.Skip("the real-ESLint regression starts a Node process per case")
	}
	command, scratchRoot := eslintFixture(t)

	cases := []struct {
		name       string
		consumer   string
		owned      string
		source     string
		wantExit   int
		wantOutput string
	}{
		{
			name:       "a TypeScript-only consumer matcher leaves .tsx outside the pre-fix block",
			consumer:   consumerTypeScriptOnly,
			owned:      preFixOwnedEslintConfig,
			source:     "src/Component.tsx",
			wantExit:   0,
			wantOutput: "no matching configuration was supplied",
		},
		{
			name:       "the generated matcher puts .tsx in front of the rules once a parser exists",
			consumer:   consumerWithParser,
			source:     "src/Component.tsx",
			wantExit:   1,
			wantOutput: "dharness/require-jsdoc",
		},
		{
			name:       "a .tsx file with no parser fails instead of passing silently",
			consumer:   consumerTypeScriptOnly,
			source:     "src/Component.tsx",
			wantExit:   1,
			wantOutput: "Parsing error",
		},
		{
			name:       "an upper-case extension is matched the way the .tsx spelling is",
			consumer:   consumerParserOnly,
			source:     "src/Upper.TSX",
			wantExit:   1,
			wantOutput: "dharness/require-jsdoc",
		},
		{
			name:       "the consumer's global ignore still wins over the owned block",
			consumer:   consumerWithGlobalIgnore,
			source:     "dist/Component.tsx",
			wantExit:   0,
			wantOutput: "matching ignore pattern",
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			dir, err := os.MkdirTemp(scratchRoot, "case-")
			if err != nil {
				t.Fatal(err)
			}
			t.Cleanup(func() { _ = os.RemoveAll(dir) })

			writeGoldenFixtureFile(t, dir, "eslint.config.mjs", tc.consumer)

			owned := tc.owned
			if owned == "" {
				owned = ownedEslintConfig(project.At(dir, dir), nil, jsconfig.ESM)
			}
			writeNestedFixtureFile(t, filepath.Join(dir, project.Dir), ownedEslintName(jsconfig.ESM), owned)
			writeNestedFixtureFile(t, filepath.Join(dir, filepath.Dir(tc.source)), filepath.Base(tc.source), unDocumentedTsx)

			output, exit := runEslint(t, command, dir, tc.source)

			if exit != tc.wantExit {
				t.Errorf("eslint exited %d, want %d\n%s", exit, tc.wantExit, output)
			}
			if !strings.Contains(output, tc.wantOutput) {
				t.Errorf("eslint output does not carry %q:\n%s", tc.wantOutput, output)
			}
		})
	}
}

// unDocumentedTsx is valid TSX and a violation of dharness/require-jsdoc at
// once, so one file answers both halves of the question: a real parser judges
// it, and the default parser cannot read it at all.
const unDocumentedTsx = "export function Panel(): number {\n  return 1;\n}\n"

// preFixOwnedEslintConfig is the block dharness wrote before this change: no
// `files`, one owned rule. It is pinned as a literal because it is the
// before-state this test exists to tell apart from the generated one — the
// generator no longer produces it, and must never produce it again.
const preFixOwnedEslintConfig = `export default function dharnessLayer({ plugin }) {
  return [
    { ignores: [".dharness/**"] },
    {
      plugins: { dharness: plugin },
      rules: {
        "dharness/require-jsdoc": "error",
      },
    },
  ];
}
`

// consumerTypeScriptOnly is the shape the bug was reported with: a matcher
// for `.ts` and nothing else, so `.tsx` is matched by no config at all. It
// doubles as the no-parser case, since a config that does not match `.tsx`
// cannot give it a parser either.
const consumerTypeScriptOnly = `import tseslint from "typescript-eslint";
import dharnessPlugin from "dharness-eslint-plugin";
import dharnessLayer from "./.dharness/eslint.config.mjs";

export default [
  { files: ["**/*.ts"], languageOptions: { parser: tseslint.parser } },
  ...dharnessLayer({ plugin: dharnessPlugin }),
];
`

// consumerWithParser is a project whose parser already covers `.tsx` — the
// case §05 protects: dharness adds no languageOptions, so this parser stays
// the one that runs.
const consumerWithParser = `import tseslint from "typescript-eslint";
import dharnessPlugin from "dharness-eslint-plugin";
import dharnessLayer from "./.dharness/eslint.config.mjs";

export default [
  ...tseslint.configs.recommended,
  ...dharnessLayer({ plugin: dharnessPlugin }),
];
`

// consumerParserOnly states the parser and no matcher of its own — a legal
// flat config, and the sharpest form of this question: the only `files` entry
// in the project belongs to the owned block, so an upper-case extension is
// linted at all only if the owned matcher folded its case.
const consumerParserOnly = `import tseslint from "typescript-eslint";
import dharnessPlugin from "dharness-eslint-plugin";
import dharnessLayer from "./.dharness/eslint.config.mjs";

export default [
  { languageOptions: { parser: tseslint.parser } },
  ...dharnessLayer({ plugin: dharnessPlugin }),
];
`

// consumerWithGlobalIgnore states an exclusion deliberately. Flat config
// makes an ignores-only object global, and the owned ignore is a second one
// beside it; neither may be read as configuration for the files it drops.
const consumerWithGlobalIgnore = `import tseslint from "typescript-eslint";
import dharnessPlugin from "dharness-eslint-plugin";
import dharnessLayer from "./.dharness/eslint.config.mjs";

export default [
  { ignores: ["dist/**"] },
  ...tseslint.configs.recommended,
  ...dharnessLayer({ plugin: dharnessPlugin }),
];
`

// eslintFixture resolves what the opt-in run needs, or skips. Command is the
// argv prefix for the fixture's ESLint — `node <eslint.js>` rather than the
// .bin shim, which is a shell script on POSIX and a .cmd on Windows and not
// something exec can always start directly.
func eslintFixture(t *testing.T) (command []string, scratchRoot string) {
	t.Helper()

	scratchRoot = os.Getenv(eslintFixtureEnv)
	if scratchRoot == "" {
		t.Skipf("%s is not set: this regression needs a disposable project with eslint, typescript-eslint and dharness-eslint-plugin installed, and says so by naming its absolute path", eslintFixtureEnv)
	}
	if !filepath.IsAbs(scratchRoot) {
		t.Fatalf("%s = %q, want an absolute path", eslintFixtureEnv, scratchRoot)
	}

	node, err := exec.LookPath("node")
	if err != nil {
		t.Fatalf("%s is set but node is not on PATH: %v", eslintFixtureEnv, err)
	}

	eslint := filepath.Join(scratchRoot, "node_modules", "eslint", "bin", "eslint.js")
	for _, want := range []string{eslint, filepath.Join(scratchRoot, "node_modules", "typescript-eslint"), filepath.Join(scratchRoot, "node_modules", "dharness-eslint-plugin")} {
		if _, err := os.Stat(want); err != nil {
			t.Fatalf("%s does not hold the dependencies this regression runs against: %v", eslintFixtureEnv, err)
		}
	}
	return []string{node, eslint}, scratchRoot
}

// runEslint starts the fixture's ESLint in dir and returns its combined
// output with its exit code, which is the verdict §11 reads.
func runEslint(t *testing.T, command []string, dir string, args ...string) (string, int) {
	t.Helper()

	cmd := exec.Command(command[0], append(append([]string{}, command[1:]...), args...)...)
	cmd.Dir = dir
	output, err := cmd.CombinedOutput()
	if err == nil {
		return string(output), 0
	}

	var exit *exec.ExitError
	if errors.As(err, &exit) {
		return string(output), exit.ExitCode()
	}
	t.Fatalf("start %v in %s: %v\n%s", command, dir, err, output)
	return "", 0
}
